server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: security-dashboard
  datasource:
    url: jdbc:h2:mem:security_dashboard
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

logging:
  level:
    dashboard: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
